### ISSUE TITLE
configure command

### ISSUE THREAD

**Issue by RYU81** [Magisk-Modules-Repo/ACSwitch#2]
i use this command but not working

acs [--configure]

sorry for stupid question

**Comment by ghost** [comment]
Please head over to my Telegram group linked in README.

**Comment by sourcevault** [comment]
is there a way to do Pulse type charging using this module - for example:
- charge for 10 seconds and then .. 
- wait for 10 seconds
- repeat till 90% is reached 

I am running this command:

`ipc --method es10`

does it work ?

should I also uninstall other apps like ACC ( advanced charge controller ) and Battery Charge Limiter (BCL), as they seem to do similar things ? would it cause disruption ?

Thanks.
