### ISSUE TITLE
Pixel 3 xl

### ISSUE THREAD

**Issue by ffuser1** [Magisk-Modules-Repo/ACSwitch#3]
States it does not work on my phone

**Comment by ghost** [comment]
Could you join the group as linked in README?

**Comment by ffuser1** [comment]
i don't have telegram and i don't want to have to install an app to report
that this doesn't work. sorry

**Comment by ghost** [comment]
OK. It's early morning here and usual routine stuff is pending. Let me get prepared for the day and then I will definitely help you on this.

**Comment by ffuser1** [comment]
I installed init.d injector. And I get this

**Comment by ghost** [comment]
@ffuser1 what? It says nothing.

**Comment by ffuser1** [comment]
in the terminal output in the image, it shows acs not working because there
is no such file or directory. and it says phone is not supported

**Comment by ghost** [comment]
It said `Your device is unfortunately not supported (No such file or directory)`, right?

**Comment by ffuser1** [comment]
correct...

**Comment by fuligana** [comment]
#3

**Comment by ghost** [comment]
I will soon provide details on how to debug compatibility on currently unsupported device in next release. Please wait until then and provide me logs thereafter.
