### ISSUE TITLE
How to know if daemon is running or not?

### ISSUE THREAD

**Issue by RHSaliya** [Magisk-Modules-Repo/ACSwitch#7]
How to know if the daemon is running? and what is automation?

**Comment by RHSaliya** [comment]
pgrep ipc

**Comment by RHSaliya** [comment]
Is there any Command?

**Comment by Jaymin-0-1910** [comment]
`ps -A | grep ipcd` will work. There's no official way. You can always run `ipc --daemon launch` to ensure it's already running.
